server:
  port: 8010
spring:
  application:
    name: selenium-service
  datasource:
    url: jdbc:mysql://localhost:3306/selenium
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
